##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: message-consumer--coverage&#61;jacoco
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
broker:
  exchange: "message-exchange"
  queueName: "message-queue"
  queueNameImpares: "message-queue-impares"
  routingKey: "message"
  routingKeyImpares: "messageImpares"